spring:
  datasource:
    name: javaweb
    url: jdbc:mysql://47.106.72.160:3306/bookshop?serverTimezone=UTC&characterEncoding=utf-8
    username: root
    password:
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: /static/**

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.test.bean