spring:
  datasource:
    name: javaweb
    url: jdbc:mysql://localhost:3306/bookshop?serverTimezone=UTC&characterEncoding=utf-8
    username: lhc
    password: 1998
    driver-class-name: com.mysql.cj.jdbc.Driver
  mvc:
    static-path-pattern: /static/**

mybatis:
  mapper-locations: classpath:mapper/*.xml
  type-aliases-package: com.example.test.bean